name: Build AyuGram Flatpak

on:
  workflow_dispatch:

env:
  TDESKTOP_API_ID: 2040
  TDESKTOP_API_HASH: b18441a1ff607e10a989891a5462e627

jobs:
  build-and-release:
    name: Build and Release Flatpak
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      IMAGE_TAG: tdesktop:centos_env

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      
      - name: First set up
        run: |
          sudo apt update
          curl -sSL https://install.python-poetry.org | python3 -
          cd Telegram/build/docker/centos_env
          poetry install
          DOCKERFILE=$(LTO= poetry run gen_dockerfile)
          echo "$DOCKERFILE" > Dockerfile
          rm -rf __pycache__
      
      - name: Free Disk Space Action
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - name: Set up Docker Buildx.
        uses: docker/setup-buildx-action@v4
  
      - name: Libraries
        uses: docker/build-push-action@v7
        with:
          context: Telegram/build/docker/centos_env
          load: ${{ env.ONLY_CACHE == 'false' }}
          tags: ${{ env.IMAGE_TAG }}
          cache-from: type=local,src=${{ runner.temp }}/.buildx-cache
          cache-to: type=local,dest=${{ runner.temp }}/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf ${{ runner.temp }}/.buildx-cache
          mv ${{ runner.temp }}/.buildx-cache{-new,}

      - name: Telegram Desktop build
        run: |
          DEFINE=""
          if [ -n "${{ matrix.defines }}" ]; then
            DEFINE="-D ${{ matrix.defines }}=ON"
            echo Define from matrix: $DEFINE
            echo "ARTIFACT_NAME=AyuGram ${{ matrix.defines }}" >> $GITHUB_ENV
          else
            echo "ARTIFACT_NAME=AyuGram" >> $GITHUB_ENV
          fi

          docker run --rm \
          -u $(id -u) \
          -v $PWD:/usr/src/tdesktop \
          $IMAGE_TAG \
          /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh \
          -D TDESKTOP_API_ID=${TDESKTOP_API_ID} \
          -D TDESKTOP_API_HASH=${TDESKTOP_API_HASH} \
          $DEFINE

      - name: Check
        run: |
          filePath="out/Release/AyuGram"
          if test -f "$filePath"; then
            echo "Build successfully done! :)"

            size=$(stat -c %s "$filePath")
            echo "File size of ${filePath}: ${size} Bytes."
          else
            echo "Build error, output file does not exist."
            exit 1
          fi

      - name: Install Flatpak SDK
        run: |
          sudo apt install -y flatpak flatpak-builder
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install --user -y --noninteractive flathub org.gnome.Sdk//48
          flatpak install --user -y --noninteractive flathub org.gnome.Platform//48

      - name: Prepare Flatpak build directory
        run: |
          mkdir -p ayugram-flatpak-build
          if [ -f out/Release/AyuGram ]; then
            cp out/Release/AyuGram ayugram-flatpak-build/
          else
            echo "Error: AyuGram binary not found!"
            exit 1
          fi
          # 
          if [ -d docs/assets/flatpak-files ]; then
            cp -r docs/assets/flatpak-files/* ayugram-flatpak-build/
          fi

      - name: Build Flatpak package
        working-directory: ./ayugram-flatpak-build
        run: |
          rm -rf repo build-dir
          #  com.ayugram.desktop.yml 
          flatpak-builder --repo=repo --force-clean --disable-rofiles-fuse build-dir com.ayugram.desktop.yml
          flatpak build-bundle repo ayugram-desktop.flatpak com.ayugram.desktop

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AyuGram-linux-flatpak
          path: ayugram-flatpak-build/ayugram-desktop.flatpak
          retention-days: 7

      - name: Generate release info
        id: release_info
        shell: bash
        run: |
          commit_sha=$(git rev-parse --short HEAD)
          timestamp=$(date +"%Y%m%d-%H%m%s")
          release_name="CI-$commit_sha-$timestamp"
          echo "commit_sha=$commit_sha" >> $GITHUB_OUTPUT
          echo "timestamp=$timestamp" >> $GITHUB_OUTPUT
          echo "release_name=$release_name" >> $GITHUB_OUTPUT

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.release_info.outputs.release_name }}
          name: "CI Build ${{ steps.release_info.outputs.commit_sha }}"
          prerelease: true
          files: ayugram-flatpak-build/ayugram-desktop.flatpak
          token: ${{ secrets.GITHUB_TOKEN }}